version: '3'

services:
        grafana:
                #image: grafana/grafana:latest
                build: my-docker-grafana
                volumes:
                        - /mnt/foobar
                ports:
                        - "3000:3000"
        db:
                #image: gr4y/docker-graphite-api:latest
                #image: brutasse/graphite-api:latest
                #image: sitespeedio/graphite
                build: my-docker-graphite
                ports:
                        - "8080:80"
                        - "2003:2003"

